---
- name: Check 'openvpn_working_directory' parameter
  assert:
    that:
      - "openvpn_working_directory is defined"
      - "openvpn_working_directory | length > 0"
    fail_msg: "parameter 'openvpn_working_directory' is missing"

- include_tasks: check-ca-parameters.yml

- name: Check 'openvpn_server_common_name' parameter
  assert:
    that:
      - "openvpn_server_common_name is defined"
      - "openvpn_server_common_name | length > 0"
    fail_msg: "parameter 'openvpn_server_common_name' is missing"

- name: Check 'openvpn_config_volume' parameter
  assert:
    that:
      - "openvpn_config_volume is defined"
      - "openvpn_config_volume | length > 0"
    fail_msg: "parameter 'openvpn_config_volume' is missing"

- name: Check 'openvpn_log_volume' parameter
  assert:
    that:
      - "openvpn_log_volume is defined"
      - "openvpn_log_volume | length > 0"
    fail_msg: "parameter 'openvpn_log_volume' is missing"

- name: Check 'openvpn_server_address' parameter
  assert:
    that:
      - "openvpn_server_address is defined"
      - "openvpn_server_address | length > 0"
    fail_msg: "parameter 'openvpn_server_address' is missing"
