---
- name: Create client certs directory
  file:
    path: "{{ openvpn_client_certs_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Create client keys directory
  file:
    path: "{{ openvpn_client_keys_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Create client csr directory
  file:
    path: "{{ openvpn_client_csr_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Create client configs directory
  file:
    path: "{{ openvpn_client_config_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- include_tasks: create-client.yml
  with_items: "{{ openvpn_clients }}"
