---
- name: Setup Diffie-Hellman parameter filename
  set_fact:
    openvpn_dh_parameter_path:
      "{{ openvpn_server_keys_directory }}/\
      dh{{ openvpn_dh_parameter_size }}.pem"

- name: clear Diffie-Hellman parameter
  file:
    path: "{{ openvpn_dh_parameter_path }}"
    state: absent
  when: openvpn_clear_dh_parameter

- name: check Diffie-Hellman parameter existence
  stat:
    path: "{{ openvpn_dh_parameter_path }}"
  register: dh_parameter_file

- name: Generate Diffie-Hellman Parameter (may take a long time)
  openssl_dhparam:
    path: "{{ openvpn_dh_parameter_path }}"
    size: "{{ openvpn_dh_parameter_size }}"
    owner: "{{ openvpn_user_uid }}"
    group: "{{ openvpn_user_uid }}"
  when: not dh_parameter_file.stat.exists
  notify: Restart openvpn service
