---
- name: Setup Diffie-Hellman parameter filename
  set_fact:
    dh_parameter_path: "{{server_keys_directory}}/dh{{dh_parameter_size}}.pem"

- name: clear Diffie-Hellman parameter
  file:
    path: "{{dh_parameter_path}}"
    state: absent
  when: clear_dh_parameter

- name: check Diffie-Hellman parameter existence
  stat:
    path: "{{dh_parameter_path}}"
  register: dh_parameter_file

- name: Generate Diffie-Hellman Parameter (may take a long time)
  openssl_dhparam:
    path: "{{dh_parameter_path}}"
    size: "{{dh_parameter_size}}"
  when: not dh_parameter_file.stat.exists
  register: dh_parameter
