---
- name: Create server keys directory
  file:
    path: "{{server_keys_directory}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Generate server private key
  openssl_privatekey:
    path: "{{server_private_key_path}}"
    size: "{{server_key_size}}"

- name: Generate server's Certificate Signing Request
  openssl_csr:
    path: "{{server_csr_path}}"
    privatekey_path: "{{server_private_key_path}}"
    common_name: "{{server_common_name}}"

- name: Generate server certificate
  openssl_certificate:
    path: "{{server_cert_path}}"
    csr_path: "{{server_csr_path}}"
    ownca_path: "{{ca_cert_path}}"
    ownca_privatekey_path: "{{ca_private_key_path}}"
    provider: ownca
