---
- name: Create server keys directory
  file:
    path: "{{server_keys_directory}}"
    state: directory
    owner: "{{openvpn_user_uid}}"
    group: "{{openvpn_user_uid}}"
    mode: 0750

- name: Generate the OpenSSL RSA private key for Server
  openssl_privatekey:
    path: "{{server_private_key_path}}"
    size: "{{server_key_size}}"
    owner: "{{openvpn_user_uid}}"
    group: "{{openvpn_user_uid}}"

- name: Generate the OpenSSL Certificate Signing Request for Server
  openssl_csr:
    path: "{{server_csr_path}}"
    privatekey_path: "{{server_private_key_path}}"
    common_name: "{{server_common_name}}"
    key_usage:
      - digitalSignature
      - keyAgreement
    extended_key_usage:
      - serverAuth
    owner: "{{openvpn_user_uid}}"
    group: "{{openvpn_user_uid}}"

- name: Generate Certificate for Server
  openssl_certificate:
    path: "{{server_cert_path}}"
    csr_path: "{{server_csr_path}}"
    ownca_path: "{{ca_cert_path}}"
    ownca_privatekey_path: "{{ca_private_key_path}}"
    provider: ownca
    owner: "{{openvpn_user_uid}}"
    group: "{{openvpn_user_uid}}"
