---
- name: Create CA directory
  file:
    path: "{{ openvpn_ca_directory }}"
    state: directory
    owner: "{{ openvpn_user_uid }}"
    group: "{{ openvpn_user_uid }}"
    mode: 0750

- name: Generate the OpenSSL RSA private key
    for Certificate Authority
  openssl_privatekey:
    path: "{{ openvpn_ca_private_key_path }}"
    size: "{{ openvpn_ca_key_size }}"
    owner: "{{ openvpn_user_uid }}"
    group: "{{ openvpn_user_uid }}"

- name: Generate the OpenSSL Certificate Signing Request
    for Certificate Authority
  openssl_csr:
    path: "{{ openvpn_ca_csr_path }}"
    privatekey_path: "{{ openvpn_ca_private_key_path }}"
    common_name: "{{ openvpn_ca_common_name }}"
    country_name: "{{ openvpn_ca_country_name }}"
    state_or_province_name: "{{ openvpn_ca_state_or_province_name }}"
    locality_name: "{{ openvpn_ca_locality_name }}"
    organization_name: "{{ openvpn_ca_organization_name }}"
    organizational_unit_name: "{{ openvpn_ca_organizational_unit_name }}"
    key_usage:
      - cRLSign
      - keyCertSign
    owner: "{{ openvpn_user_uid }}"
    group: "{{ openvpn_user_uid }}"

- name: Generate Certificate for Certificate Authority
  openssl_certificate:
    path: "{{ openvpn_ca_cert_path }}"
    privatekey_path: "{{ openvpn_ca_private_key_path }}"
    csr_path: "{{ openvpn_ca_csr_path }}"
    provider: selfsigned
    owner: "{{ openvpn_user_uid }}"
    group: "{{ openvpn_user_uid }}"

- name: Read CA Certificate
  slurp:
    src: "{{ openvpn_ca_cert_path }}"
  register: ca_cert
