---
- name: Create docker working directory
  file:
    path: "{{ openvpn_docker_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Template dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ openvpn_docker_working_directory }}/Dockerfile"
    owner: root
    group: root
    mode: 0644
  register: dockerfile

- name: Build dockerimage
  docker_image:
    build:
      path: "{{ openvpn_docker_working_directory }}"
      pull: false
    name: "{{ openvpn_image_name }}"
    tag: "{{ openvpn_version }}"
    source: build
    state: present
    force_source: "{{
      dockerfile.changed
      or openvpn_force_build
      }}"
  notify: Restart openvpn service
