---
- name: Setup variables for Cert
  set_fact:
    client_private_key_path: "{{client_keys_directory}}/{{item}}.key.pem"
    client_csr_path: "{{client_csr_directory}}/{{item}}.csr.pem"
    client_cert_path: "{{client_certs_directory}}/{{item}}.cert.pem"

- name: Generate an OpenSSL RSA private key
  openssl_privatekey:
    path: "{{client_private_key_path}}"
    size: "{{client_cert_size}}"

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{client_csr_path}}"
    privatekey_path: "{{client_private_key_path}}"
    common_name: "{{item}}"

- name: Generate self-singed client certificate
  openssl_certificate:
    path: "{{client_cert_path}}"
    csr_path: "{{client_csr_path}}"
    ownca_path: "{{ca_cert_path}}"
    ownca_privatekey_path: "{{ca_private_key_path}}"
    provider: ownca
