---
- include_tasks: check-parameters.yml
- include_tasks: install-requirements.yml
- include_tasks: create-certificate-authority.yml
- include_tasks: create-server-certificate.yml
- include_tasks: create_dh_parameter.yml
- include_tasks: setup-openvpn-config.yml
- include_tasks: create-docker-image.yml
- include_tasks: create-tls-auth-parameter.yml
- include_tasks: create-clients.yml
- include_tasks: setup-systemd-service.yml
- include_tasks: setup-logrotate.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Start openvpn service (if not started)
  service:
    name: "{{ openvpn_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
