---
- include: check-parameters.yml
- include: install-requirements.yml
- include: create-certificate-authority.yml
- include: create-server-certificate.yml
- include: create_dh_parameter.yml
- include: setup-openvpn-config.yml
- include: create-docker-image.yml
- include: create-tls-auth-parameter.yml
- include: create-clients.yml
- include: setup-systemd-service.yml
- include: setup-logrotate.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Start openvpn service (if not started)
  service:
    name: "{{ service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
