---
- name: Create systemd unit file
  template:
    src: openvpn.systemd.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart openvpn service

- name: Enable service
  service:
    name: "{{ service_name }}"
    enabled: true
  register: openvpn_service
  changed_when: openvpn_service.changed
    or openvpn_service.status.SubState != 'running'
  notify: Start openvpn service
