---
- name: Create log volume
  file:
    path: "{{ log_volume }}"
    state: directory
    owner: "{{ openvpn_user_uid }}"
    group: "{{ openvpn_user_uid }}"
    mode: 0750

- name: Setup logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/openvpn
