---
- name: Create systemd unit file
  template:
    src: openvpn.systemd.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart openvpn service
