---
- name: Restart openvpn service
  systemd:
    name: "{{ openvpn_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
