---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Start openvpn service
  service:
    name: "{{ service_name }}"
    state: started
  register: openvpn_service_start

- name: Restart openvpn service
  service:
    name: "{{ service_name }}"
    state: restarted
  when: not (
    openvpn_service_start is defined
    and openvpn_service_start.changed
    )
