---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-openvpn-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-openvpn-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-openvpn-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-openvpn-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-openvpn-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-openvpn-noble:
        clients_dir: vagrant-openvpn-noble
      ansible-openvpn-jammy:
        clients_dir: vagrant-openvpn-jammy
      ansible-openvpn-focal:
        clients_dir: vagrant-openvpn-focal
      ansible-openvpn-bookworm:
        clients_dir: vagrant-openvpn-bookworm
      ansible-openvpn-bullseye:
        clients_dir: vagrant-openvpn-bullseye

verifier:
  name: ansible
