---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-openvpn-noble
    image: docker.io/borisskert/python3:noble
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-openvpn-jammy
    image: docker.io/borisskert/python3:jammy
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-openvpn-focal
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker

  - name: ansible-openvpn-bookworm
    image: docker.io/borisskert/python3:bookworm
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian
  - name: ansible-openvpn-bullseye
    image: docker.io/borisskert/python3:bullseye
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-openvpn-noble:
        clients_dir: docker-openvpn-noble
      ansible-openvpn-jammy:
        clients_dir: docker-openvpn-jammy
      ansible-openvpn-focal:
        clients_dir: docker-openvpn-focal
      ansible-openvpn-bookworm:
        clients_dir: docker-openvpn-bookworm
      ansible-openvpn-bullseye:
        clients_dir: docker-openvpn-bullseye

verifier:
  name: ansible
