---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-openvpn-focal
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-openvpn-bionic
    image: docker.io/borisskert/python3:bionic
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-openvpn-xenial
    image: docker.io/borisskert/python3:xenial
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-openvpn-buster
    image: docker.io/borisskert/python3:buster
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian
  - name: ansible-openvpn-stretch
    image: docker.io/borisskert/python3:stretch
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-openvpn-stretch:
        clients_dir: docker-openvpn-stretch
      ansible-openvpn-buster:
        clients_dir: docker-openvpn-buster
      ansible-openvpn-focal:
        clients_dir: docker-openvpn-focal
      ansible-openvpn-bionic:
        clients_dir: docker-openvpn-bionic
      ansible-openvpn-xenial:
        clients_dir: docker-openvpn-xenial

verifier:
  name: ansible
