---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-openvpn
      openvpn_alpine_version: '3.21'
      openvpn_version: 2.6.12
      openvpn_working_directory: /srv/openvpn
      openvpn_ca_common_name: mydomain.org
      openvpn_ca_country_name: US
      openvpn_ca_state_or_province_name: CA
      openvpn_ca_locality_name: San Francisco
      openvpn_ca_organization_name: Fort-Funston
      openvpn_ca_email_address: me@mydomain.org
      openvpn_ca_organizational_unit_name: IT Division
      openvpn_server_common_name: openvpn.mydomain.org
      openvpn_server_address: vpn.mydomain.org
      openvpn_ca_key_size: 2048
      openvpn_server_key_size: 2048
      openvpn_dh_parameter_size: 2048
      openvpn_client_cert_size: 2048
      openvpn_download_dir: "./.tmp/{{ clients_dir }}"
      openvpn_tls_version_min: 1.3
      openvpn_verbosity: 9
      openvpn_server_ip: 10.0.0.1
      openvpn_network_ip: 10.0.0.0
      openvpn_subnet_mask: 255.255.0.0
      openvpn_clients:
        - name: vpnclient01
          passphrase: abc
        - name: vpnclient02
