---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-openvpn
      alpine_version: '3.11'
      openvpn_version: 2.4.8
      working_directory: /srv/openvpn
      ca_common_name: mydomain.org
      ca_country_name: US
      ca_state_or_province_name: CA
      ca_locality_name: San Francisco
      ca_organization_name: Fort-Funston
      ca_email_address: me@mydomain.org
      ca_organizational_unit_name: IT Division
      server_common_name: openvpn.mydomain.org
      server_address: vpn.mydomain.org
      ca_key_size: 2048
      server_key_size: 2048
      dh_parameter_size: 1024
      client_cert_size: 2048
      download_dir: "./.tmp/{{ clients_dir }}"
      tls_version_min: 1.3
      verbosity: 9
      server_ip: 10.0.0.1
      network_ip: 10.0.0.0
      subnet_mask: 255.255.0.0
      clients:
        - name: vpnclient01
          passphrase: abc
        - name: vpnclient02
